### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by OzKnight2013**
## discription
Add fingerprint for Kona 2019 Petrol Non-SCC

### CODE REVIEW

**Comment by arne182** [comment]
Please only add the missing signals 1064: 8, 1151: 6 etc. To the first fingerprint.

**Comment by arne182** [comment]
There should be 8 new key pairs added to that FP

**Comment by OzKnight2013** [comment]
I believe the first fp is for the Kona without radar.

**Comment by arne182** [comment]
With fingerprints it is the more the merrier. As long as it is from the same car type. There is very little need to have more than one per car type. Just add the missing numbers inbetween the first one and it will work to satisfy the Travis check.

**Comment by arne182** [comment]
Like this is how it should be done.

**Pull request closed without merging**
