### PR TITLE
change "limit" to "speedlimit"

### PR DESCRIPTION
**Pull request by rav4kumar**

### CODE REVIEW

**Comment by arne182** [comment]
Are you sure there is enough space

**Comment by arne182** [comment]
Please load it up and send me a picture of how it looks

**Comment by rav4kumar** [comment]
Alright, I will do it once I get my back from delearship

**Comment by arne182** [comment]
Think we only have 9 spaces but if it looks ok we can change it.

**Comment by rav4kumar** [comment]
https://imgur.com/gallery/Xi3wXB3

here is the picture.

**Comment by rshtirmer** [comment]
Do you know if it looks ok if there is a space between "speed" and "limit," or is that pushing it?

**Comment by arne182** [comment]
It is already one font size smaller. Looks good Kumar.

**Pull request merged**
