### PR TITLE
074 clean

### PR DESCRIPTION
**Pull request by arne182**
Fix trademarked name
Enable cloak
add Lexus UXH TSS2 support

### CODE REVIEW

**Comment by arne182** [comment]
If it will not work then why the Cease and desist!?
@GreatGozzaofLaw I will wait for your advice.
Looks like openpilot™ is becoming closedpilot.
So you suggest I disable the logger completely on all 28 of the devices @geohot?

**Comment by geohot** [comment]
It is still fraud, even if you are technically blocked as well.

We don't care if you disable the logger or not, that's on the users device, which we don't own. We do own our servers, and you, or anyone running this fork, does not have authorization to access them. We do not want any data from any devices running this fork.

We suggest you remove all code accessing comma.ai's servers.

**Comment by mbuboltz1024** [comment]
The company is so ignorant on what they are doing.

**Comment by geohot** [comment]
99% percent of our users recognize the serious safety implications in using this stuff. For the 1% who don't (28 is under 1%), we don't want anything at all to do with. Don't use our trademark, don't post in our discord, and don't connect to our servers. We don't want to be confused with you, we don't want to hear from you, and we don't want your users on our servers. How is this ignorant?

This is so far beyond the pale: http://archive.vn/BA2y3

**Comment by GreatGozzaofLaw** [comment]
I'm again going to have to chime in here again. If you don't want him accessing your servers then have everyone else who forked Comma Ai's OpenPilot cut off from having access to your servers. Over 3.6K+ have OpenPilot forked, and I guarantee you that there are more then 100+ forks out there on GitHub that have more safety implication issues then Arne. However your targeting of him specifically which is seriously starting to sound like harassment. And continuing to add to this situation George in the original comment you only told him to change the name, nothing about connection to the server, why are you continuing to revise comments? You are borderline starting to violate the MIT license George. QUOTE: "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so"

**Comment by geohot** [comment]
Arne had a choice to implement a reasonable safety policy in this fork. The other forks did. He didn't, and responded with http://archive.vn/BA2y3

I suggest you revert the "cloak" as well. You are still misidentifying yourself to our servers. This is fraud and theft of service.

**Comment by jyoung8607** [comment]
> Over 3.6K+ have OpenPilot forked, and I guarantee you that there are more then 100+ forks out there on GitHub that have more safety implication issues then Arne.

Name a few in common use.

> However your targeting of him specifically which is seriously starting to sound like harassment. 

Name some of the other forks that attempted to bypass the access controls on Comma's backend infrastructure and I'm sure they'll be addressed.

> And continuing to add to this situation George in the original comment you only told him to change the name, nothing about connection to the server, why are you continuing to revise comments?

Original announcement:
Annotation 2020-04-09 204526

> You are borderline starting to violate the MIT license George. QUOTE: "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so"

Nobody asked him to take down any code. He can log to his own backend if he likes.

I didn't come here to slam Arne or his works, some of which (like mapd) I'm a fan of. I came here because there's a lot of misinformation flying around that is unnecessarily divisive to the community.

Here's the facts: the other major forks, like Kegman and Dragonpilot, got on board with the culture of safety and negotiated ways to meet their users needs in good faith, and for them the matter is closed. This fork stands alone in its choices, and trying to bypass Comma backend access controls is a very loud statement of intent going forward.
Edit by arne182: my fork too removing 10x driver monitoring and unsafe high braking limit and even being the first to commit to the unsafe panda code which was required, which got rejected, George has done this before in the past promising things and just plainly forgetting about his promises. 
https://github.com/commaai/panda/pull/476

**Comment by arne182** [comment]
Let us deal with this like this. If you remove the server ban on my fork(which you said would be on the 10 th and activated it earlier) then I have no need to protect my fork users from you banning their dongle ID's . Even the prime users who are paying you for your services you are banning. I wonder if you must reimburse them for the not offering them the service they are paying for.
Thank you @GreatGozzaofLaw to coming to the aid.

**Pull request merged**
