### PR TITLE
add new auto-df model, fix global df mod

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

**Comment by sshane** [comment]
@rav4kumar can you test to make sure it doesn't crash? i think it should be good to go but don't want to merge another failing change lol

**Comment by arne182** [comment]
ERROR: lib.dynamic_follow (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lib.dynamic_follow
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/tmp/openpilot/selfdrive/controls/lib/dynamic_follow/__init__.py", line 11, in <module>
    from selfdrive.controls.lib.dynamic_follow.auto_df import predict
  File "/tmp/openpilot/selfdrive/controls/lib/dynamic_follow/__init__.py", line 11, in <module>
    from selfdrive.controls.lib.dynamic_follow.auto_df import predict
  File "/tmp/openpilot/selfdrive/controls/lib/dynamic_follow/auto_df.py", line 7, in <module>
    wb = np.load('/data/openpilot/selfdrive/controls/lib/dynamic_follow/auto_df_weights.npz', allow_pickle=True)
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/openpilot/selfdrive/controls/lib/dynamic_follow/auto_df_weights.npz'

**Comment by rav4kumar** [comment]
I will test this changes on my way home. It should be fine since shanes fork works just fine. But I'll test it to see if it breaks any arne's features.

**Comment by sshane** [comment]
testing now

**Pull request merged**
