### PR TITLE
0710 clean first sync 

### PR DESCRIPTION
**Pull request by rav4kumar**
Everything from 077 works accept trafficd (just have not tested), custome arneEvents, just need to change the default params to be on instead of being off (such as osm).

### CODE REVIEW

**Comment by rav4kumar** [comment]
before this merge readme need to be re-done.

**Comment by debugged-tech** [comment]
@rav4kumar 0710-clean does not work for everyone you might want to consider waiting before merging into release4

**Comment by rav4kumar** [comment]
@debugged-hosting what is the problem that you are having ? we have not heard anything regarding that.

**Comment by debugged-tech** [comment]
@rav4kumar I have posted a couple of times on the discord but when I do a clean install of 0710-clean it installs fine but once I hook up to the vehicle it freezes. It works well on stock openpilot 0710 & stock 0.8. It also works well on dragonpilot 0.8.

**Pull request closed without merging**
